#!/bin/bash

#########################
# Some Alias Defintions #
#########################

alias speedtest='python3 ~/GIT/nanosecond/speedtest-cli'
alias dus='du -shc * | sort -hr'
alias less='more -spd'
alias lsblk='lsblk && sudo fdisk -l'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias grep='grep --colour=always'

alias bc='bc -l'
