#! /bin/bash

#########################COPYRIGHT NOTICE################################
#Copyright (C) 2013 cypher-neo (github.com/cypher-neo)                  #
#                                                                       #
#This program is free software; you can redistribute it and/or          #
#modify it under the terms of the GNU General Public License            #
#as published by the Free Software Foundation; either version 2         #
#of the License, or (at your option) any later version.                 #
#                                                                       #
#This program is distributed in the hope that it will be useful,        #
#but WITHOUT ANY WARRANTY; without even the implied warranty of         #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          #
#GNU General Public License for more details.                           #
#                                                                       #
#You should have received a copy of the GNU General Public License      #
#along with this program; if not, write to the                          #
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,       #
#Boston, MA  02110-1301, USA.#                                          #
#########################################################################

#Adds a keyfile to the Linux package system. Must be used as root
#USAGE: apt-key-test
#Then just follow the instructions

function apt-keyadd()
{
echo -e "This script MUST be run as root in order to work. You will be prompted for your password later.\n\nWould you like to add an 8-digit key or a keyfile\n"
        select keymenuchoice in "8-digit-key" "Keyfile" "Exit"
                do
                        case "$keymenuchoice" in
                                "8-digit-key")
                                        echo -n "Enter the pub key please: "
                                        read key
                                        echo -n "Enter the keyserver url please: "
                                        read keyserver
                                        sudo apt-key adv --keyserver $keyserver --recv-keys $key
                                return
                                ;;
                                "Keyfile")
                                        echo -n "Enter the URL to the keyfile please: "
                                        read url
                                        wget $url -O- | sudo apt-key add -
                                return
                                ;;
				"Exit")
					exit 2
				return
				;;
                        esac
                done
}
