#! /bin/bash/

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

function apt-stuff()
{
clear
select aptmenuchoice in "Edit APT Preferences" "Edit Sources" "Install Build Dependencies" "Add Keys" "APT History"
do
	case "$aptmenuchoice" in
	"Edit APT Preferences")
		echo "Tweaking APT Preferences can lead to system instability. Be careful out there!"
		pressanykey
		sudo nano /etc/apt/preferences
		return
	;;
	"Edit Sources")
		echo "Tweaking sources can lead to system instability. Be careful out there!"
		pressanykey
		sudo nano /etc/apt/sources.list
		return
	;;
	"Install Build Dependencies")
		sudo aptitude install debhelper devscripts build-essential
		return
	;;
	"Add Keys")
		echo "This script MUST be run as root in order to work. You will be prompted for your password later. Would you like to add an 8-digit key or a keyfile"
		        select keymenuchoice in "8 Digit Key" "Keyfile"
		                do
					case "$keymenuchoice" in
						"8 Digit Key")
							echo -n "Enter the pub key please: "
							read key
		                            		echo -n "Enter the keyserver url please"
							read keyserver
							sudo apt-key adv --keyserver $keyserver --recv-keys $key
        	        	        return
						;;
						"Keyfile")
							echo -n "Enter the URL to the keyfile please: "
							read url
							wget $url -O- | sudo apt-key add -
					return
						;;
					esac
				done
		return
        ;;
	"APT History")
		select aptmenuchoice in "Installed Programs" "Upgraded Programs" "Removed Programs"
		do
			case "$aptmenuchoice" in
			"Installed Programs")
			echo "Do you want to see every program you've ever installed, or just the last few?"
				select installmenuchoice in all limited
				do
					case "$installmenuchoice" in
					"all")
						cat /var/log/dpkg.log | grep ' installed'
						return
					;;
					"limited")
						echo "Enter how many lines you wish to see of the INSTALL log:"
						read limitnumber
						cat /var/log/dpkg.log | grep ' installed' | tail -n $limitnumber
						return
					;;
					esac
				done
				;;
			"Upgraded Programs")
			echo "Do you want to see every program upgraded, or just the last few?"
				select upgrademenuchoice in all limited
				do
					case "$upgrademenuchoice" in
					"all")
						cat /var/log/dpkg.log | grep ' upgrade'
						return
						;;
					"limited")
						echo "Enter how many lines you wish to see of the UPGRADE log:"
						read limitnumber
						cat /var/log/dpkg.log | grep ' upgrade' | tail -n $limitnumber
						return
						;;
					esac
				done
				;;
			"Removed Programs")
			echo "Do you want to see every program removed, or just the last few?"
				select removemenuchoice in all limited
				do
					case "$removemenuchoice" in
					"all")
						cat /var/log/dpkg.log | grep ' remove'
						return
						;;
					"limited")
						echo "Enter how many lines you wish to see of the REMOVAL log:"
						read limitnumber
						cat /var/log/dpkg.log | grep ' remove' | tail -n $limitnumber
						return
						;;
					esac
				done
			esac
		done
	esac
done
}
