#! /bin/bash/

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

function view_dpkg_log()
{
log_type="$1"   # e.g., "installed", "upgrade", or "remove"
echo "Do you want to see every program $log_type, or just the last few?"
	select view_choice in "All" "Limited"; do
		case "$view_choice" in
			"All")
				grep " $log_type" /var/log/dpkg.log
				return
				;;
			"Limited")
				echo "Enter how many lines you wish to see:"
				read -r limitnumber
				grep " $log_type" /var/log/dpkg.log | tail -n "$limitnumber"
				return
				;;
		esac
	done
}

function apt-stuff()
{
clear
select apt_choice in "Edit APT Preferences" "Edit Sources" "Install Build Dependencies" "Add Keys" "APT History"; do
		case "$apt_choice" in
			"Edit APT Preferences")
				echo "Tweaking APT Preferences can lead to system instability. Be careful out there!"
				pressanykey
				sudo nano /etc/apt/preferences
				return
				;;
			"Edit Sources")
				echo "Tweaking sources can lead to system instability. Be careful out there!"
				pressanykey
				sudo nano /etc/apt/sources.list
				return
				;;
			"Install Build Dependencies")
				sudo aptitude install debhelper devscripts build-essential
				return
				;;
			"Add Keys")
				echo "This script MUST be run as root. You will be prompted for your password later."
				echo "Would you like to add an 8-digit key or a keyfile?"
				select key_choice in "8-Digit Key" "Keyfile"; do
					case "$key_choice" in
						"8-Digit Key")
							echo -n "Enter the pub key: "
							read -r key
							echo -n "Enter the keyserver URL: "
							read -r keyserver
							sudo apt-key adv --keyserver "$keyserver" --recv-keys "$key"
							return
							;;
						"Keyfile")
							echo -n "Enter the URL to the keyfile: "
							read -r url
							wget "$url" -O- | sudo apt-key add -
							return
							;;
					esac
				done
				;;
			"APT History")
				select history_choice in "Installed Programs" "Upgraded Programs" "Removed Programs"; do
					case "$history_choice" in
						"Installed Programs")
							view_dpkg_log "installed"
							return
							;;
						"Upgraded Programs")
							view_dpkg_log "upgrade"
							return
							;;
						"Removed Programs")
							view_dpkg_log "remove"
							return
							;;
					esac
				done
				;;
		esac
	done
}
