#!/bin/bash

function autoinstaller()
{
echo -e "${Color009}This will copy the backup of your installed files from /var/cache/apt/archives into a Backup folder in your Downloads. Assuming you haven't cleaned this location recently, it should get everything you installed."
pressanykey
cd $HOME/Downloads
mkdir Backup
cd /var/cache/apt/archives
for i in *.deb
	do
		cp $i $HOME/Downloads/Backup
	done
echo -e "${Color009}Backup complete. Move the saved files to a flash drive before formatting your computer."
pressanykey
exit 0
}
