#!/bin/bash

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

## This is just a little hack I wrote to dim the screen brightness  when the function keys responsible for screen dimming don't work.
function bright() {
	echo "Brightness Controller"
	echo "Select brightness level (10-100):"
	select level in "10" "20" "30" "40" "50" "60" "70" "80" "90" "100"; do
		if [[ "$level" =~ ^[0-9]+$ ]]; then
		# Calculate brightness as a decimal (e.g., 10 -> 0.1)
			brightness=$(echo "scale=1; $level / 100" | bc)
			xrandr --output eDP1 --brightness "$brightness"
			return
		else
			echo "Invalid selection, please choose a brightness level between 10 and 100."
		fi
	done
}
