#!/bin/bash

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

#Proper usage: catgrapple [FILE] [SEARCH TERM]

function catgrapple()
{
# Use awk once, storing line numbers in the `lines` array
	mapfile -t lines < <(awk -v "search=$2" '$0 ~ search { print NR }' "$1")
# Iterate over the `lines` array, opening each match in nano one at a time
	for i in "${lines[@]}"
		do
# Open the file in nano at the specified line
		terminator -x nano "+$i" "$1"
# Prompt to continue to the next match
		read -p "Press Enter to open the next match..."
		done
}
