#!/bin/bash

###################################
# LOOK! IT'S A RAINBOW OF COLORS! #
###################################
color() { printf "\e[38;5;%sm" "$1"; }  # Use color codes as arguments
bold()  { printf "\e[1;38;5;%sm" "$1"; } # Bold versions
reset() { printf "\e[0m"; }              # Reset to default

function color_rainbow()
{
for i in {0..255}; do echo -e "\e[38;05;${i}m color ${i}\e[0m"; done | less
}

function bold_rainbow()
{
for i in {0..255}; do echo -e "\e[1;38;05;${i}m bold ${i}\e[0m"; done | less
}

function color_waterfall()
{
while : ; do for i in {000..255}; do echo -e "\e[38;05;${i}m Color${i}\e[0m"; sleep .1 ; done ; done
}
