#!/bin/bash

###################################
# LOOK! IT'S A RAINBOW OF COLORS! #
###################################
color() { printf "\e[38;5;%sm" "$1"; }  # Use color codes as arguments
bold()  { printf "\e[1;38;5;%sm" "$1"; } # Bold versions
reset() { printf "\e[0m"; }              # Reset to default

function color_rainbow() {
    for i in {0..255}; do
        printf "\e[38;5;%sm color %s\e[0m\n" "$i" "$i"
    done | less -R
}

function bold_rainbow() {
    for i in {0..255}; do
        printf "\e[1;38;5;%sm bold %s\e[0m\n" "$i" "$i"
    done | less -R
}

function color_waterfall() {
    while : ; do
        for i in {0..255}; do
            # %s drops the variable $i into the ANSI code and the text string
            printf "\e[38;5;%sm Color%s\e[0m\n" "$i" "$i"
            sleep .1
        done
    done
}