#! /bin/bash/

#########################COPYRIGHT NOTICE################################
#Copyright (C) 2013 Sean Murphy (github.com/cypher-neo)			#
#									#
#This program is free software; you can redistribute it and/or		#
#modify it under the terms of the GNU General Public License		#
#as published by the Free Software Foundation; either version 2		#
#of the License, or (at your option) any later version.			#
#									#
#This program is distributed in the hope that it will be useful,	#
#but WITHOUT ANY WARRANTY; without even the implied warranty of		#
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the		#
#GNU General Public License for more details.				#
#									#
#You should have received a copy of the GNU General Public License	#
#along with this program; if not, write to the				#
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,	#
#Boston, MA  02110-1301, USA.#						#
#########################################################################

function makelefthandpasses()
{
</dev/urandom tr -dc '12345!@#$%qwertQWERTasdfgASDFGzxcvZXCV' | head -c $length; echo ""
}

function makerighthandpasses()
{
</dev/urandom tr -dc '67890^&*()uiopUIOPhjklHJKLbnm,.BNM<>' | head -c $length; echo ""
}

function makepsuedorandompasses()
{
< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c $length;echo;
}

function makehexadecimalpasses()
{
</dev/urandom tr -dc [:xdigit:] | head -c $length; echo ""
}

function createpass()
{
echo "How many passwords?"
read num
echo "How long should the passwords be in length?"
read length

echo -e "The following selections are available to you."
select passchoice in "Left Hand" "Right Hand" "Pseudorandom" "Hexadecimal" "Quit Without Selection"
do
	case "$passchoice" in
			"Left Hand")
				for ((i = 0; i < num; ++i))
                                        do
                                                makelefthandpasses >> LeftHandPasswordSheet
                                        done
                        return
			;;
			"Right Hand")
                                for ((i = 0; i < num; ++i))
                                        do
                                                makerighthandpasses >> RightHandPasswordSheet
                                        done
				return
			;;
			"Pseudorandom")
                                for ((i = 0; i < num; ++i))
                                        do
                                                makepsuedorandompasses >> PsuedoRandomPasswordSheet
                                        done
				return
			;;
			"Hexadecimal")
                                for ((i = 0; i < num; ++i))
                                        do
                                                makehexadecimalpasses >> HexadecimalPasswordSheet
                                        done
				return
                        ;;
			"Quit Without Selection")
                                exit 1
				return
			;;
	esac
done
}
