#! /bin/bash

#function fluxstart()
#{
#nohup compton -b &
#synclient HorizEdgeScroll=1
#synclient VertEdgeScroll=1
#synclient TapButton1=1
#nohup nm-applet &
#nohup mintupdate-launcher &
#nohup xscreensaver -no-splash &
#killall conky &
#conky -c ~/GIT/conked-out/.conkyrc-flux2 &
#}
