#! /bin/bash

cp ~/.bashrc ~/.bashrc.bkup
sudo echo ". ~/GIT/nanosecond/bashrc" >> ~/.bashrc
sudo cp ~/GIT/nanosecond/sources/sources.list /etc/apt/
sudo cp ~/GIT/nanosecond/sources/sourcestopper /etc/apt/preferences.d/

sudo cp ~/GIT/nanosecond/default.nanorc /usr/share/nano/
sudo apt update

if ! dpkg -l | grep -q aptitude; then sudo apt install aptitude; else echo "aptitude already installed. Skipping."; fi
if ! dpkg -l | grep -q apt-transport-https; then sudo apt install apt-transport-https; else echo "apt-transport-https already installed. Skipping."; fi
if ! dpkg -l | grep -q apt; then sudo apt install apt; else echo "apt already installed. Skipping."; fi
if ! dpkg -l | grep -q bash-completion; then sudo apt install bash-completion; else echo "bash-completion already installed. Skipping."; fi
if ! dpkg -l | grep -q concalc; then sudo apt install concalc; else echo "concalc already installed. Skipping."; fi
if ! dpkg -l | grep -q curl; then sudo apt install curl; else echo "curl already installed. Skipping."; fi
if ! dpkg -l | grep -q dirmngr; then sudo apt install dirmngr; else echo "dirmngr already installed. Skipping."; fi
if ! dpkg -l | grep -q inxi; then sudo apt install inxi; else echo "inxi already installed. Skipping."; fi
if ! dpkg -l | grep -q wget; then sudo apt install wget; else echo "wget already installed. Skipping."; fi
if ! dpkg -l | grep -q software-properties-common; then sudo apt install software-properties-common; else echo "software-properties-common already installed. Skipping."; fi
if ! dpkg -l | grep -q systemd-timesyncd; then sudo apt install systemd-timesyncd; else echo "systemd-timesyncd already installed. Skipping."; fi
