#!/bin/bash

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

function InstallWhenNotExist()
{
if ! dpkg -l | grep -wq $1; then echo -e "Working on ${Color196}$1${Color_Off}" && sudo apt install $1; else echo -e "${Color196}$1${Color_Off} is installed"; fi
#sudo aptitude install -P $1
}

function ForceInstallWhenNotExist()
{
if ! dpkg -l | grep -wq $1; then echo -e "Working on ${Color196}$1${Color_Off}" && sudo aptitude install -Py $1; else echo "${Color196}$1${Color_Off} is installed"; fi
#sudo aptitude install -P $1
}

function InstallAllWhenNotExist()
{
if ! dpkg -l | grep -wq $1; then echo -e "Working on ${Color196}$1${Color_Off}" && sudo aptitude install -Pr $1; else echo "${Color196}$1${Color_Off} is installed"; fi
#sudo aptitude install -Pr $1
}

function installstuff()
{
echo -e "Showing you your sources.list. ${Color196}If anything looks off, abort the script immediately and fix it!${Color_Off}\n"
grep -e "stable" -e "testing" -e "unstable" -e "contrib" -e "non-free" /etc/apt/sources.list
	pressanykey
		InstallWhenNotExist software-properties-common
select installmenuchoice in "Install Debian Mods" "Continue Without Debian Mods"
	do
		case "$installmenuchoice" in
			"Install Debian Mods")
				sudo apt update
##				echo "PPA CHECK - checking for missing repos."
##					if ! ls /etc/apt/sources.list.d | grep -iq "crawl"
##						then
##							echo "Adding Dungeon Crawl Stone Soup PPA"
##							sudo sh -c 'echo "deb https://crawl.develz.org/debian crawl 0.22" >> /etc/apt/sources.list.d/crawl.list'
##							wget https://crawl.develz.org/debian/pubkey -O - | sudo apt-key add -
##						else
##							echo "Dungeon Crawl Stone Soup PPA already there."
##					fi
##				pressanykey
					echo -e "Checking for FlatPak"
					InstallWhenNotExist flatpak
					InstallWhenNotExist gnome-software-plugin-flatpak
					flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
				pressanykey
				sudo apt update
				installstuff
			return
			;;
			"Continue Without Debian Mods")
				keepinstallingmorestuff
			return
			;;
		esac
	done
}

function keepinstallingmorestuff()
{
clear
echo -e "Options:\n"
echo -e "Compressed Files - gzip p7zip tar unrar"
echo -e "Conky - conky-all"
echo -e "Documents - libreoffice kate"
echo -e "Drive Management - smartmontools apper mintstick"
echo -e "File Browsers - dolphin dolphin4 spacefm"
echo -e "Fluxbox Setup - Installs required files for my personal Fluxbox setup"
echo -e "Font Managers - font-manager gucharmap figlet"
echo -e "Fonts - lots of nice fonts"
echo -e "Fortunes - Can install fortune files that you can use in various programs"
echo -e "Games - crawl dosbox zangband"
echo -e "Internet - chromium firefox htop mtr namebench netselect-apt strace Telegram-Desktop torbrowser-launcher"
echo -e "IRC - hexchat konversation"
echo -e "Media - flac lame moc smplayer vlc"
echo -e "Pictures - inkscape luminance-hdr gimp kde-spectacle ufraw"
echo -e "Terminal - konsole terminator"
echo -e "Torrents - amule deluge ktorrent qbittorrent transmission-gtk"
echo -e "Virtualbox - non-free version of virtualbox"
echo -e "WINE - Automates the WINE installation"
echo -e "X Screensavers - xscreensaver xscreensaver-data xscreensaver-data-extra xscreensaver-screensaver-bsod xscreensaver-gl xscreensaver-gl-extra rss-glx"
echo -e "What do you wish to install?\n\n"
select installmenuchoice in "Compressed Files" "Conky" "Documents" "Drive Management" "File Browsers" "Fluxbox Setup" "Font Managers" "Fonts" "Fortunes" "Games" "Internet" "IRC" "Media" "Pictures" "Terminal" "Torrents" "Virtualbox" "WINE" "X Screensavers" "Exit"
	do
		case "$installmenuchoice" in
			"Compressed Files")
			        InstallWhenNotExist gzip
                                InstallWhenNotExist p7zip-full
                                InstallWhenNotExist tar
                                InstallWhenNotExist unrar-free
                                InstallWhenNotExist unzip
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Conky")
				InstallAllWhenNotExist conky-all
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Documents")
				InstallWhenNotExist kate
				InstallWhenNotExist libreoffice
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Drive Management")
				InstallWhenNotExist smartmontools
				InstallWhenNotExist apper
				chromium http://packages.linuxmint.com/pool/main/m/mintstick/
				google-chrome http://packages.linuxmint.com/pool/main/m/mintstick/
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"File Browsers")
				InstallWhenNotExist dolphin
				InstallWhenNotExist dolphin4
                                InstallWhenNotExist spacefm
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Fluxbox Setup")
				InstallAllWhenNotExist conky-all
				InstallWhenNotExist compton
				InstallWhenNotExist deluge
				InstallWhenNotExist fluxbox
				InstallWhenNotExist hexchat
				InstallWhenNotExist hpanel
				InstallWhenNotExist network-manager-gnome
				InstallWhenNotExist suckless-tools
				InstallWhenNotExist spacefm
				InstallWhenNotExist terminator
				InstallWhenNotExist xfce4-power-manager
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Font Managers")
				InstallWhenNotExist figlet
				InstallWhenNotExist font-manager
				InstallWhenNotExist gucharmap
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Fonts")
				InstallWhenNotExist fonts-arkpandora
				InstallWhenNotExist fonts-averia-gwf
				InstallWhenNotExist fonts-averia-sans-gwf
				InstallWhenNotExist fonts-averia-serif-gwf
				InstallWhenNotExist fonts-cabin
				InstallWhenNotExist fonts-cantarell
				InstallWhenNotExist fonts-cardo
				InstallWhenNotExist fonts-century-catalogue
				InstallWhenNotExist fonts-comfortaa
				InstallWhenNotExist fonts-dejavu
				InstallWhenNotExist fonts-dejavu-core
				InstallWhenNotExist fonts-dejavu-extra
				InstallWhenNotExist fonts-dkg-handwriting
				InstallWhenNotExist fonts-dseg
				InstallWhenNotExist fonts-droid
				InstallWhenNotExist fonts-dosis
				InstallWhenNotExist fonts-ebgaramond
				InstallWhenNotExist fonts-ebgaramond-extra
				InstallWhenNotExist fonts-essays1743
				InstallWhenNotExist fonts-georgewilliams
				InstallWhenNotExist fonts-glasstty
				InstallWhenNotExist fonts-gnutypewriter
				InstallWhenNotExist fonts-go
				InstallWhenNotExist fonts-hack-ttf
				InstallWhenNotExist fonts-junicode
				InstallWhenNotExist fonts-jura
				InstallWhenNotExist fonts-kristi
				InstallWhenNotExist fonts-lato
				InstallWhenNotExist fonts-linex
				InstallWhenNotExist fonts-liberation
				InstallWhenNotExist fonts-lobster
				InstallWhenNotExist fonts-lobstertwo
				InstallWhenNotExist fonts-sil-abyssinica
				InstallWhenNotExist fonts-noto
				InstallWhenNotExist fonts-play
				InstallWhenNotExist fonts-roboto
				InstallWhenNotExist fonts-wine
				InstallWhenNotExist ttf-aenigma
				InstallWhenNotExist ttf-engadget
				InstallWhenNotExist ttf-mscorefonts-installer
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Fortunes")
				InstallWhenNotExist fortunes
				InstallWhenNotExist fortune-mod
				InstallWhenNotExist fortunes-spam
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Games")
				InstallWhenNotExist steam-launcher
				InstallWhenNotExist dosbox
				InstallWhenNotExist zangband
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Internet")
				InstallWhenNotExist chromium
				InstallWhenNotExist htop
				InstallWhenNotExist mtr
				InstallWhenNotExist namebench
				InstallWhenNotExist netselect-apt
				InstallWhenNotExist strace
				InstallWhenNotExist telegram-desktop
				InstallWhenNotExist torbrowser-launcher
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"IRC")
				InstallWhenNotExist hexchat
				InstallWhenNotExist konversation
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Media")
				InstallWhenNotExist flac
				InstallWhenNotExist lame
				InstallWhenNotExist moc
				InstallWhenNotExist smplayer
				InstallWhenNotExist vlc
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Pictures")
				InstallWhenNotExist inkscape
				InstallWhenNotExist luminance-hdr
				InstallWhenNotExist gimp
				InstallWhenNotExist gimp-data-extras
				InstallWhenNotExist gimp-gap
				InstallWhenNotExist gimp-lensfun
				InstallWhenNotExist gimp-ufraw
				InstallWhenNotExist gimp-texturiz
				InstallWhenNotExist gwenview
				InstallWhenNotExist kde-spectacle
				InstallWhenNotExist ufraw
				InstallWhenNotExist ufraw-batch
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Terminal")
				InstallWhenNotExist konsole
				InstallWhenNotExist terminator
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Torrents")
				InstallWhenNotExist amule
				InstallWhenNotExist deluge
				InstallWhenNotExist ktorrent
				InstallWhenNotExist qbittorrent
				InstallWhenNotExist transmission-gtk
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"Virtualbox")
				InstallAllWhenNotExist virtualbox-nonfree
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"WINE")
				sudo dpkg --add-architecture i386
				wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
				sudo apt-add-repository https://dl.winehq.org/wine-builds/debian/
				sudo apt update
				sudo apt install winehq-stable
				pressanykey
				clear
				keepinstallingmorestuff
			return
			;;
			"X Screensavers")
				InstallWhenNotExist xscreensaver
				InstallWhenNotExist xscreensaver-data
				InstallWhenNotExist xscreensaver-data-extra
				InstallWhenNotExist xscreensaver-screensaver-bsod
				InstallWhenNotExist xscreensaver-gl
				InstallWhenNotExist xscreensaver-gl-extra
				InstallWhenNotExist rss-glx
				pressanykey
				clear
				keepinstallingmorestuff
				return
			;;
			"Exit")
				return
			;;
		esac
	done
}
