#!/bin/bash

#########################COPYRIGHT NOTICE################################
#									#
#This program is free software; you can redistribute it and/or          #
#modify it under the terms of the GNU General Public License            #
#as published by the Free Software Foundation; either version 2         #
#of the License, or (at your option) any later version.                 #
#                                                                       #
#This program is distributed in the hope that it will be useful,        #
#but WITHOUT ANY WARRANTY; without even the implied warranty of         #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          #
#GNU General Public License for more details.                           #
#                                                                       #
#You should have received a copy of the GNU General Public License      #
#along with this program; if not, write to the                          #
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,       #
#Boston, MA  02110-1301, USA.#                                          #
#########################################################################

function InstallWhenNotExist()
{
if ! dpkg -l | grep -wq $1; then sudo aptitude install -P $1; else echo $1 "is installed"; fi
#sudo aptitude install -P $1
}

function ForceInstallWhenNotExist()
{
if ! dpkg -l | grep -wq $1; then sudo aptitude install -Py $1; else echo $1 "is installed"; fi
#sudo aptitude install -P $1
}

function InstallAllWhenNotExist()
{
if ! dpkg -l | grep -wq $1; then sudo aptitude install -Pr $1; else echo $1 "is installed"; fi
#sudo aptitude install -Pr $1
}

function installstuff()
{
ForceInstallWhenNotExist konsole
	echo -e "Add Testing and \"contrib non-free\" to your sources list at /etc/apt/sources.list before running this script.\n"
	pressanykey
	sudo nano /etc/apt/sources.list
	pressanykey
	echo "PPA CHECK - checking for missing repos."
		if ! ls /etc/apt/sources.list.d | grep -iq "getdeb"
			then
				echo "Adding GetDeb PPA"
				wget -q -O - http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
				sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu zesty-getdeb apps" >> /etc/apt/sources.list.d/getdeb.list'
				sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu zesty-getdeb games" >> /etc/apt/sources.list.d/getdeb.list'
				sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu yakkety-getdeb apps" >> /etc/apt/sources.list.d/getdeb.list'
				sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu yakkety-getdeb games" >> /etc/apt/sources.list.d/getdeb.list'
			else
				echo "GetDeb PPA is already there."
		fi
			sudo aptitude update
		clear
		echo -e "All Right! We're starting the install... Hold on tight!\n"
		pressanykey
		        InstallWhenNotExist gzip
                        InstallWhenNotExist p7zip-full
                        InstallWhenNotExist tar
                        InstallWhenNotExist unrar-free
                        InstallWhenNotExist unzip
			InstallWhenNotExist kate
#			InstallWhenNotExist libreoffice## Find the updated version online
			InstallWhenNotExist curl
			InstallWhenNotExist terminator
			InstallWhenNotExist gucharmap
			InstallWhenNotExist fonts-arkpandora
			InstallWhenNotExist fonts-averia-gwf
			InstallWhenNotExist fonts-averia-sans-gwf
			InstallWhenNotExist fonts-averia-serif-gwf
			InstallWhenNotExist fonts-cabin
			InstallWhenNotExist fonts-cantarell
			InstallWhenNotExist fonts-dejavu
			InstallWhenNotExist fonts-dejavu-core
			InstallWhenNotExist fonts-dejavu-extra
			InstallWhenNotExist fonts-droid
			InstallWhenNotExist fonts-dosis
			InstallWhenNotExist fonts-georgewilliams
			InstallWhenNotExist fonts-junicode
			InstallWhenNotExist fonts-jura
			InstallWhenNotExist fonts-lato
			InstallWhenNotExist fonts-linex
			InstallWhenNotExist fonts-liberation
			InstallWhenNotExist fonts-lobster
			InstallWhenNotExist fonts-lobstertwo
			InstallWhenNotExist fonts-sil-abyssinica
			InstallWhenNotExist fonts-noto
			InstallWhenNotExist fonts-play
			InstallWhenNotExist ttf-mscorefonts-installer
			InstallWhenNotExist fonts-roboto
			InstallWhenNotExist fonts-wine
##			InstallWhenNotExist chromium## Find Google Chrome
			InstallWhenNotExist namebench
			InstallWhenNotExist netselect-apt
			InstallWhenNotExist flac
			InstallWhenNotExist lame
			InstallWhenNotExist moc
			InstallWhenNotExist smplayer
			InstallWhenNotExist vlc
			InstallWhenNotExist gimp
			InstallWhenNotExist gimp-data-extras
			InstallWhenNotExist gimp-gap
			InstallWhenNotExist gimp-lensfun
			InstallWhenNotExist gimp-ufraw
			InstallWhenNotExist gimp-texturize
			InstallWhenNotExist gwenview
			InstallWhenNotExist terminator
			InstallWhenNotExist xscreensaver
			InstallWhenNotExist xscreensaver-data
			InstallWhenNotExist xscreensaver-data-extra
			InstallWhenNotExist xscreensaver-screensaver-bsod
}
