#!/bin/bash

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

#################################################################################################################################
# Modified Julian Date can be read about at http://en.wikipedia.org/wiki/Julian_day						#
#																#
# This realtime clock converts the current date to Modified JD and displays both in realtime.					#
#################################################################################################################################

function juliantime()
{
	# Get the current date and time components just once
	todayis=$(date +"%F")
	hourtime=$(date +"%H")
	minutetime=$(date +"%M")
	secondtime=$(date +"%S")

	# Compute Julian Day once outside the loop
	let julian=(`date +%s -d $todayis`-`date +%s -d 1968-05-24`)/86400+40000

	# Infinite loop for real-time conversion
	while true
	do
		# Re-fetch the time in the loop
		hourtime=$(date +"%H")
		minutetime=$(date +"%M")
		secondtime=$(date +"%S.%N" | head -c10)

		# Compute Julian time as a float
		juliantime=$(echo "scale=9; ($hourtime / 24) + ($minutetime / 1440) + ($secondtime / 86400) + $julian" | bc -l)

		# Clear the screen and display results
		clear
		echo "Standard Gregorian Date"
		echo "$todayis $hourtime:$minutetime:$secondtime"
		echo "Modified Julian"
		echo "$juliantime"

		# Sleep for a small fraction of a second (to update frequently without excessive CPU usage)
		sleep 0.01
	done
}
