#! /bin/bash

function khmedia()
{
clear
echo -e "${Color011}Please follow the directions to use this script. This script will pause so you can read the directions. If you have not completed all these steps, close the Terminal so the program aborts completely.\n\n1. Create a /Music/ folder in $HOME/Downloads\n2. Make sure the SD card is mounted at /dev/sdb1 and that the mount label is ONE WORD, preferably KHmedia\n3.If you have already downloaded the music, put it in the $HOME/Downloads/Music and run this script in that location.\n\n${SSAlertRed01}CAUTION!!${Color_Off}${Color196}YOU MUST RUN THIS SCRIPT FROM INSIDE THE $HOME/Downloads/Music FOLDER WHICH WILL CONTAIN THE DOWNLOADED MUSIC.\nIF YOU HAVE NOT STARTED THE SCRIPT IN THE CORRECT LOCATION, ABORT THIS SCRIPT IMMEDIATELY BY CLOSING THE TERMINAL.${Color_Off}"
pressanykey
clear
echo -e "${Color011}I'm going to check the folder for the music zip files, and download them if necessary."
pressanykey
clear
ls -A > folderlist
if ! grep -q "snnw_E.mp3.zip" folderlist
	then
		echo -e "${Color196}Downloading snnw_E.mp3.zip${Color_Off}"
		wget http://download.jw.org/files/media_books/95/snnw_E.mp3.zip
	else
		echo -e "${Color046}snnw_E.mp3.zip is in this directory. No need to download that."
fi
if ! grep -q "iasn_E.mp3.zip" folderlist
	then
		echo -e "${Color196}Downloading iasn_E.mp3.zip${Color_Off}"
		wget http://download.jw.org/files/media_music/c0/iasn_E.mp3.zip
	else
		echo -e "${Color046}iasn_E.mp3.zip is in this directory. No need to download that."
fi
rm folderlist
echo -e "${Color011}All downloaded!${Color_Off}\n${Color196}I'm going to extract the media files now, and rename them so they will transfer in the correct order.${Color_Off}"
pressanykey
clear
if [ -a *snnw*.zip ]
	then
		echo -e "${Color196}Extracting media from ${RedAlert}snnw_E.mp3.zip${Color_Off}"
		unzip -q *snnw*.zip
fi
if [ -a *iasn*.zip ]
	then
		echo -e "${Color196}Extracting media from ${RedAlert}iasn_E.mp3.zip${Color_Off}"
		unzip -q *iasn*.zip
fi
mv *mp3.zip $HOME
find -name "*snnw*" -type f | rename 's/snnw/iasn/g'
musicsource=$(pwd)
echo -e "${Color046}I've moved the zip files to $HOME in case you need them again.${Color_Off}"
pressanykey
clear
echo -e "${Color011}The working directory is: ${Color196}$musicsource${Color_Off}"
khtemp=$(mount | column -t | grep sdb1 | expand | awk '{ print $3 }')
khfoldera=$(echo -e "/A/")
khdrivea=$(echo -e $khtemp$khfoldera)
khfolderz=$(echo -e "/Z/")
khdrivez=$(echo -e $khtemp$khfolderz)
echo -e "${Color011}The KH card is mounted here: ${Color196}$khtemp${Color_Off}"
echo -e "${Color011}And the first folder I'm going to create and fill is: ${Color196}$khdrivea${Color_Off}"
pressanykey
mkdir $khdrivea
rsync -ravP ${musicsource}/ ${khdrivea}
echo -e "${Color010}Stage 1 Complete!${Color_Off}"
pressanykey
echo -e "${Color011}And the final folder I'm going to create and fill is: ${Color196}$khdrivez${Color_Off}"
mkdir ${khdrivez}
pressanykey
rsync -ravP ${musicsource}/ ${khdrivez}
echo -e "${Color010}Everything's Done!${Color_Off}"
pressanykey
}
