#! /bin/bash/

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

function packagelistreinstaller()
{
echo "Make a backup list of programs installed, or reinstall from a backup list?"
                        select packagelist in "Backup List" "Reinstall Backup"
                                do
                                        case "$packagelist" in
                                        "Backup List")
                                                cd
                                                sudo dpkg-query -f '${binary:Package}\n' -W > packages_list.txt
                                                return
                                                ;;
                                        "Reinstall Backup")
                                                cd
						if grep -q i386 packages_list.txt ; then echo "Found i386. Installing i386 architecture"; sudo dpkg --add-architecture i386 ; fi
                                                sudo xargs -a packages_list.txt apt install
                                                return
                                                ;;
                                        esac
                                done
}

