#!/bin/bash

function passwordmaker()
{
select passwordchoice in "Memorable Passwords" "Large Password Sheet"
	do
		case "$passwordchoice" in
			"Memorable Passwords")
				clear
				shuf /usr/share/dict/words | head -n4
			return
			;;
			"Large Password Sheet")
				clear
				if ! dpkg -l | grep -q makepasswd; then sudo aptitude install -Pr makepasswd; fi
				clear
				echo -e "(This script runs 14 iterations to generate a variety of passwords.\nYou will get 14x the number you enter here. I reccommend you keep the number under 20 to avoid too much lag.)\nHow many passwords?"
				read num
				echo "Minimum length of each password?"
				read minimum
				echo "Maximum length?"
				read maximum
				clear
				Numbers="1234567890"
				Lowers="qwertyuiopasdfghjklzxcvbnm"
				Uppers="QWERTYUIOPASDFGHJKLZXCVBNM"
				Symbols="!@#$%^&*();:<>/?"
				echo -e "Numbers, Lowercase, Uppercase, Symbols" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Numbers$Lowers$Uppers$Symbols" >> passwordmakerfile
				echo -e "\nNumbers, Lowercase, Symbols" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Numbers$Lowers$Symbols" >> passwordmakerfile
				echo -e "\nNumbers, Lowercase, Uppercase" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Numbers$Lowers$Uppers" >> passwordmakerfile
				echo -e "\nNumbers, Symbols" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Numbers$Symbols" >> passwordmakerfile
				echo -e "\nNumbers, Uppercase" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Numbers$Uppers" >> passwordmakerfile
				echo -e "\nNumbers, Lowercase" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Numbers$Lowers" >> passwordmakerfile
				echo -e "\nNumbers" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Numbers" >> passwordmakerfile
				echo -e "\nLowercase, Uppercase, Symbols" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Lowers$Uppers$Symbols" >> passwordmakerfile
				echo -e "\nLowercase, Symbols" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Lowers$Symbols" >> passwordmakerfile
				echo -e "\nLowercase, Uppercase" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Lowers$Uppers" >> passwordmakerfile
				echo -e "\nLowercase" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Lowers" >> passwordmakerfile
				echo -e "\nUppercase, Symbols" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Uppers$Symbols" >> passwordmakerfile
				echo -e "\nUppercase" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Uppers" >> passwordmakerfile
				echo -e "\nSymbols" >> passwordmakerfile
				makepasswd --count $num --minchars $minimum --maxchars $maximum --string "$Symbols" >> passwordmakerfile
			return
			;;
		esac
	done
}
