#! /bin/bash/

function rebash()
{
echo -e "Run Update BEFORE Upgrade"
select rebashchoice in "Reset BASH" "Update Menu" "Upgrade Menu"
do
	case "$rebashchoice" in
		"Reset BASH")
			clear
			source ~/.bashrc || return
		return
		;;
		"Update Menu")
			select updatechoice in "Update Sources" "NetSelect Best Source"
				do
					case "$updatechoice" in
						"Update Sources")
							sudo apt update || return
							return
						;;
						"NetSelect Best Source")
							cd ~/GIT
							if ls "sources.list"
								then
									echo "Removing old sources"
									rm sources.list
								else
									echo "old sources.list not found"
							fi
							echo "Creating new sources list"
							sudo netselect-apt -sn
							return
						;;
					esac
				done
			return
			;;
		"Upgrade Menu")
			select upgradechoice in "List Upgrades" "List Upgrades with Detail" "Run Safe-Upgrade" "Run Full-Upgrade" "Autoremove Unrequired"
				do
					case "$upgradechoice" in
						"List Upgrades")
							apt list --upgradable 2>/dev/null | cut -d/ -f1 | sort | column
							return
						;;
						"List Upgrades with Detail")
							sudo apt list --upgradeable
							return
						;;
						"Run Safe-Upgrade")
							sudo apt upgrade || return
							return
						;;
						"Run Full-Upgrade")
							sudo apt full-upgrade || return
							return
						;;
						"Autoremove Unrequired")
							sudo apt autoremove || return
							return
						;;
					esac
				done
		return
		;;
	esac
done
}
