#! /bin/bash/

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

function rebash()
{
echo -e "Run Update BEFORE Upgrade"
select rebashchoice in "Reset BASH" "Update Menu" "Upgrade Menu"
do
	case "$rebashchoice" in
		"Reset BASH")
			clear
			source ~/.bashrc || return
		return
		;;
		"Update Menu")
			select updatechoice in "Update Sources" "NetSelect Best Source"
				do
					case "$updatechoice" in
						"Update Sources")
							sudo apt update || return
							return
						;;
						"NetSelect Best Source")
							cd ~/GIT
							if ls "sources.list"
								then
									echo "Removing old sources"
									rm sources.list
								else
									echo "old sources.list not found"
							fi
							echo "Creating new sources list"
							sudo netselect-apt -sn
							return
						;;
					esac
				done
			return
			;;
		"Upgrade Menu")
			select upgradechoice in "List Upgrades" "Run Safe-Upgrade" "Run Full-Upgrade"
				do
					case "$upgradechoice" in
						"List Upgrades")
							sudo apt list --upgradeable
							return
						;;
						"Run Safe-Upgrade")
							sudo apt upgrade || return
							return
						;;
						"Run Full-Upgrade")
							sudo apt full-upgrade || return
							return
						;;
					esac
				done
		return
		;;
	esac
done
}
