#! /bin/bash/

#########################COPYRIGHT NOTICE################################
#Copyright (C) 2013 cypher-neo (github.com/cypher-neo)			#
#									#
#This program is free software; you can redistribute it and/or		#
#modify it under the terms of the GNU General Public License		#
#as published by the Free Software Foundation; either version 3		#
#of the License, or (at your option) any later version.			#
#									#
#This program is distributed in the hope that it will be useful,	#
#but WITHOUT ANY WARRANTY; without even the implied warranty of		#
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the		#
#GNU General Public License for more details.				#
#									#
#You should have received a copy of the GNU General Public License	#
#along with this program; if not, write to the				#
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,	#
#Boston, MA  02110-1301, USA.#						#
#########################################################################

######################CERTIFICATE OF AUTHENTICITY########################
#You should have downloaded this script from github.com. If you paid    #
#anything while obtaining a copy of this script, demand a refund, and   #
#get the current version of this script for free from:                  #
#               https://github.com/cypher-neo/nanosecond                #
#########################################################################

function tradedisplay()
{
	clear
	format="%10s\t%10s\t%10s\n"
	printf "$format" "Item" "Low" "High"
	printf "$format" "====" "===" "===="
	for (( i = 0 ; i < ${#item[@]} ; i++ ))
	do
		printf "$format" ${item[$i]} ${low[$i]} ${high[$i]}
	done
	read -n1 -sp "Press any key to continue, or CTRL+C to quit."
}

function getPrice(){
	for (( i = 0 ; i < ${#item[@]} ; i++ ))
	do
		read -p "Price of ${item[$i]}: " current[$i]
		if [[ ${low[$i]} == ${item[$i]} ]]; then low[$i]=${current[$i]};fi
		if [[ ${high[$i]} == ${item[$i]} ]]; then high[$i]=${current[$i]};fi
		if [[ current[$i] > high[$i] ]]; then high[$i]=${current[$i]};fi
		if [[ current[$i] < low[$i] ]]; then low[$i]=${current[$i]};fi
	done
}

# MAIN PROGRAM
declare -a item=(Salt Tea Wine Amber Oil Weapons Parchment Indigo Rugs Gunpower)
declare -a low=(${item[@]})
declare -a current=(${item[@]})
declare -a high=(${item[@]})
while :
do
	clear
	echo -e "Enter the current prices"
	getPrice "${item[@]}"
	tradedisplay
done
