#! /bin/bash/

#########################COPYRIGHT NOTICE################################
#Copyright (C) 2013 cypher-neo (github.com/cypher-neo)			#
#									#
#This program is free software; you can redistribute it and/or		#
#modify it under the terms of the GNU General Public License		#
#as published by the Free Software Foundation; either version 2		#
#of the License, or (at your option) any later version.			#
#									#
#This program is distributed in the hope that it will be useful,	#
#but WITHOUT ANY WARRANTY; without even the implied warranty of		#
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the		#
#GNU General Public License for more details.				#
#									#
#You should have received a copy of the GNU General Public License	#
#along with this program; if not, write to the				#
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,	#
#Boston, MA  02110-1301, USA.#						#
#########################################################################

function webstuff()
{
clear
echo -e "Where do you wish to go?"
select webchoice in "Show Network Infos" "Update DNS"
do
	case "$webchoice" in
		"Show Network Infos")
			select networkchoice in "Network Interface" "IP's and Subnets"
			do
				case "$networkchoice" in
					"Network Interface")
						clear
						netstat -rn
					return
					;;
					"IP's and Subnets")
						clear
						/sbin/ifconfig
					return
					;;
				esac
			done
		return
		;;
		"Update DNS")
			clear
				echo -e "First I'll run namebench to determine the fastest DNS servers for you to use.\nAfter this is done, edit your connection to add your DNS settings.\n\n"
				pressanykey
				namebench
		return
		;;
	esac
done
}
