#! /bin/bash

function welcomeaptcount()
{
## List number of available updates
aptcount=$(aptitude search "~U" | wc -l)

#List updates available
if [ "$aptcount" = "0" ] # if there are no updates available
        then
                echo -e "There are no known upgrades available for your system."
elif [ "$aptcount" = "1" ] # if there is 1 update only
        then
                echo -e "There is ${Color208}1 known upgrade${Color_Off} available for your system.\nType ${Color014}rebash${Color_Off} to begin the update/upgrade process."
else [ "$aptcount" != "1" ] # there is more than 1 update
                echo -e "There are ${Color196}$aptcount known upgrades${Color_Off} available for your system.\nType ${Color014}rebash${Color_Off} to begin the update/upgrade process."
fi
}
