#! /bin/bash/

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

function welcome()
{
# who am i?
username=$(whoami)

###########################################################
# You could add a Tasklist to your BASH prompt like this! #
###########################################################
#taskline="${Color201}Task List${Color_Off}\n$(cat -n $HOME/BASH/Tasklist)"

#fortuneline="${Color201}Random Fortune Cookie${Color_Off}\n$(fortune)"

###########
# Welcome #
###########

#screenfetch

welcome1
welcomeontime

## List number of available updates
aptcount=$(aptitude search "~U" | wc -l)

#List updates available
if [ "$aptcount" = "0" ] # if there are no updates available
        then
                echo -e "There are no known upgrades available for your system."
elif [ "$aptcount" = "1" ] # if there is 1 update only
        then
                echo -e "There is ${Color208}1 known upgrade${Color_Off} available for your system."
else [ "$aptcount" != "1" ] # there is more than 1 update
                echo -e "There are ${Color196}$aptcount known upgrades${Color_Off} available for your system."
fi

#Fortune
#echo -e "\n$fortuneline"
#or
#echo -e "$fortuneline"
}
