#! /bin/bash

function welcome()
{
# who am i?
username=$(whoami)

###########################################################
# You could add a Tasklist to your BASH prompt like this! #
###########################################################
#taskline="${Color201}Task List${Color_Off}\n$(cat -n $HOME/BASH/Tasklist)"


###################
# Welcome Options #
###################

#screenfetch

###########
# Fortune #
###########
#fortuneline="${Color201}Random Fortune Cookie${Color_Off}\n$(fortune)"

#echo -e "\n$fortuneline"
#echo -e "$fortuneline"

##################
# Welcome Prompt #
##################
welcome1
welcomeaptcount
welcomeontime
}
