#! /bin/bash/

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

function welcome()
{
# who am i?
username=$(whoami)

###########################################################
# You could add a Tasklist to your BASH prompt like this! #
###########################################################
#taskline="${Color201}Task List${Color_Off}\n$(cat -n $HOME/BASH/Tasklist)"


###################
# Welcome Options #
###################

#screenfetch

###########
# Fortune #
###########
#fortuneline="${Color201}Random Fortune Cookie${Color_Off}\n$(fortune)"

#echo -e "\n$fortuneline"
#echo -e "$fortuneline"

##################
# Welcome Prompt #
##################
#welcome1
#welcomeontime
welcomeaptcount
}
