#!/bin/bash

####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE#####COPYRIGHT NOTICE####
#Copyright (C) 2018 exarobibliologst (github.com/exarobibliologist)                                                             #
#                                                                                                                               #
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License      #
#as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.          #
#                                                                                                                               #
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of #
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                     #
#                                                                                                                               #
#You should have received a copy of the GNU General Public License along with this program; if not, write to the                #
#Free Software Foundation, Inc.                                                                                                 #
#51 Franklin Street, Fifth Floor,                                                                                               #
#Boston, MA  02110-1301, USA.                                                                                                   #
#################################################################################################################################

function zangmath()
{
echo -e "What's the Current XP?\n"
read xp

select zangmenu in "BOOKS" "RODS/STAFF/WAND/JEWELERY" "WEAPONS" "OIL FLASKS" "RINGS" "SCROLLS/TORCHES" "FOOD/POTIONS" "MONEY"
	do
		case "$zangmenu" in
			"BOOKS")
				echo "How many are you converting?"
				read gimme
				concalc "15root($gimme*100000)"
				echo -e "\nTOTAL XP ="
				concalc "$xp + ($gimme*100000)"
				echo "OR"
				concalc "$xp * (15root($gimme*100000))"
			return
			;;
			"RODS/STAFF/WAND/JEWELERY")
				echo "How many charges are you converting?"
				read gimme
				concalc "15root($gimme*12500)"
				echo -e "\nTOTAL XP ="
				concalc "$xp + ($gimme*12500)"
				echo "OR"
                                concalc "$xp * (15root($gimme*12500))"
			return
			;;
			"WEAPONS")
				echo "How many weapons are you converting?"
				read gimme
                                concalc "15root($gimme*10000)"
				echo -e "\nTOTAL XP ="
				concalc "$xp + ($gimme*10000)"
				echo "OR"
                                concalc "$xp * (15root($gimme*10000))"
			return
			;;
			"OIL FLASKS")
				echo "How many flasks are you converting?"
				read gimme
                                concalc "15root($gimme*7500)"
				echo -e "\nTOTAL XP ="
				concalc "$xp + ($gimme*7500)"
                                echo "OR"
                                concalc "$xp * (15root($gimme*7500))"
			return
			;;
			"RINGS")
				echo "How many rings are you converting?"
				read gimme
                                concalc "15root($gimme*5000)"
				echo -e "\nTOTAL XP ="
				concalc "$xp + ($gimme*5000)"
				echo "OR"
                                concalc "$xp * (15root($gimme*5000))"
			return
			;;
			"SCROLLS/TORCHES")
				echo "How many scrolls are you converting?"
				read gimme
                                concalc "15root($gimme*2500)"
				echo -e "\nTOTAL XP ="
				concalc "$xp + ($gimme*2500)"
				echo "OR"
                                concalc "$xp * 15root($gimme*2500))"
			return
			;;
			"FOOD/POTIONS")
				echo "How much are you converting?"
				read gimme
                                concalc "15root($gimme*1000)"
				echo -e "\nTOTAL XP ="
				concalc "$xp + ($gimme*1000)"
				echo "OR"
                                concalc "$xp * (15root($gimme*1000))"
			return
			;;
			"MONEY")
				echo "How many turns of light / money are you converting?"
				read gimme
                                concalc "15root($gimme)"
				echo "TOTAL XP ="
				concalc "$xp + $gimme"
				echo "OR"
                                concalc "$xp * (15root($gimme))"
			return
			;;
		esac
	done
}
